### ISSUE TITLE
Sewtap rotation angle corrections

### ISSUE THREAD

**Issue by ghost** [sparkfun/LilyPad_Coin_Cell_Battery_Holder-Switched#9]
I think the angle of the top right and bottom right sewtaps need to be adjusted so that they match the angle of the corresponding pads on the left side. Specifically, I think the bottom right sewtap needs to have an angle of 0 instead of 10, and the top right should have an angle of 115 not 125.

I think these changes are minimal enough as to not necessitate reproto.

**Comment by ADataDate** [comment]
Done! Thanks
